blank_issues_enabled: true
contact_links:
  - name: Questions & Support
    url: https://github.com/kunalsuri/ai-fication-kit/discussions
    about: Please ask questions and get support in GitHub Discussions.
